### ISSUE TITLE
Bug in data

### ISSUE THREAD

**Issue by ArdaIcmez** [ozymaxx/sketchautocompletion#8]
Feature Extractor gives out exception when processing one single stroke which is either a line or a dot.

**Comment by ozymaxx** [comment]
Amir, we use the issues dashboard in order to follow the progress of bugfixes much easier. FYI

**Comment by amirSayyafan** [comment]
The xml files of missing sketches  are not complete and because of that server doesn't accept them.

**Comment by amirSayyafan** [comment]
2 of the xml files are complete but one of them is horizontal line and the other one is vertical line.

**Comment by amirSayyafan** [comment]
All of the sketches are vertical or horizontal.
